variable "availability_zones" {
  type = list(string)
  default = [
    "",
  ]
}

variable "cluster_subnet_database_id" {
  description = "List of database subnet ids"
  type        = list(string)
}

variable "cluster_subnet_group_name" {
  description = "DB cluster database subnet name"
  type        = string
  default     = "main"
}

variable "cluster_root_password_length" {
  description = "Length of autogenerated root password"
  type        = number
  default     = 16
}

variable "vpc_id" {
  description = "VPC ID for SG"
  type        = string
}

variable "private_subnets" {
  type        = list(string)
  description = "A list of all private subnets IDs."
}

variable "tags" {
  description = "tags"
  type        = map(any)
}

variable "properties" {
  type = any
}

variable "vpc_cidr" {
  type = string
}