variable "availability_zones" {
  type = list(string)
  default = [
    "",
  ]
}

variable "cluster_engine" {
  type = string
}

variable "engine_version" {
  type = string
}

variable "database_name" {
  type = string
}

variable "master_username" {
  type = string
}

variable "backup_retention_period" {
  type = string
}

variable "storage_encrypted" {
  type = string
}

variable "apply_immediately" {
  type = string
}

variable "serverless_scaling_configuration_max_capacity" {
  type = string
}

variable "serverless_scaling_configuration_min_capacity" {
  type = string
}


variable "cluster_subnet_database_id" {
  description = "List of database subnet ids"
  type        = list(string)
}

variable "cluster_subnet_group_name" {
  description = "DB cluster database subnet name"
  type        = string
  default     = "main"
}

variable "cluster_root_password_length" {
  description = "Length of autogenerated root password"
  type        = number
  default     = 16
}

variable "vpc_id" {
  description = "VPC ID for SG"
  type        = string
}

variable "private_subnets" {
  type        = list(string)
  description = "A list of all private subnets IDs."
}

variable "tags" {
  description = "tags"
  type        = map(any)
}

variable "vpc_cidr" {
  type = string
}

variable "instance_class" {
  type = string
}

variable "engine_mode" {
  type = string
}

variable "enable_http_endpoint" {
  type = string
}

variable "public_subnets" {
  type        = list(string)
  description = "A list of all public subnets IDs."
}
